ERA5_DICTIONARY = {
    "10u":    {'long_name': '10m_u_component_of_wind',              'filename': '10m_u_component_of_wind_stream-oper_daily-mean.nc'},
    "10v":    {'long_name': '10m_v_component_of_wind',              'filename': '10m_v_component_of_wind_0_daily-mean.nc'},
    "d2m":    {'long_name': '2m_dewpoint_temperature',              'filename': '2m_dewpoint_temperature_0_daily-mean.nc'},
    "t2m":    {'long_name': '2m_temperature',                       'filename': '2m_temperature_0_daily-mean.nc'},
    "tp":     {'long_name': 'total_precipitation',                  'filename': 'total_precipitation_0_daily-mean.nc'},
    'sst':    {'long_name': 'sea_surface_temperature',              'filename': 'sea_surface_temperature_0_daily-mean.nc'},
    'skt':    {'long_name': 'skin_temperature',                     'filename': 'skin_temperature_0_daily-mean.nc'},
    'fal':    {'long_name': 'forecast_albedo',                      'filename': 'forecast_albedo_0_daily-mean.nc'},
    'siconc': {'long_name': 'sea_ice_cover',                        'filename': 'sea_ice_cover_0_daily-mean.nc'},
    'tcwv':   {'long_name': 'total_column_water_vapour',            'filename': 'total_column_water_vapour_0_daily-mean.nc'},
    'ssrd':   {'long_name': 'surface_solar_radiation_downwards',    'filename': 'surface_solar_radiation_downwards_0_daily-mean.nc'},
    'strd':   {'long_name': 'surface_thermal_radiation_downwards',  'filename': 'surface_thermal_radiation_downwards_0_daily-mean.nc'},
    'tclw':   {'long_name': 'total_column_cloud_liquid_water',      'filename': 'total_column_cloud_liquid_water_0_daily-mean.nc'},
    'tciw':   {'long_name': 'total_column_cloud_ice_water',         'filename': 'total_column_cloud_ice_water_0_daily-mean.nc'},
    'sf':     {'long_name': 'snowfall',                             'filename': 'snowfall_0_daily-mean.nc'},
    'e':      {'long_name': 'evaporation',                          'filename': 'evaporation_0_daily-mean.nc'},
    'ictl1':  {'long_name': 'ice_temperature_layer_1',              'filename': 'ice_temperature_layer_1_0_daily-mean.nc'},
    'ictl2':  {'long_name': 'ice_temperature_layer_2',              'filename': 'ice_temperature_layer_2_0_daily-mean.nc'},
    'ictl3':  {'long_name': 'ice_temperature_layer_3',              'filename': 'ice_temperature_layer_3_0_daily-mean.nc'},
    'ictl4':  {'long_name': 'ice_temperature_layer_4',              'filename': 'ice_temperature_layer_4_0_daily-mean.nc'},
}